### ISSUE TITLE
cant change the language

### ISSUE THREAD

**Issue by mukhma0c** [collabora/whisper-live#19] opened 2023-07-15 08:06 UTC
i'm not sure if what i'm doing is right but adjusting the language string to "ar" didn't switch to Arabic and was still showing English.

**Comment by zoq** [comment] 2023-07-15 15:21
Did you change the model as well?

https://github.com/collabora/whisper-live/blob/main/server.py#L54

If you want any other language other than english you need to switch to `small`instead of `small.en` or `medium` instead of `medium.en`.

**Comment by makaveli10** [comment] 2023-07-17 16:45
Closed by https://github.com/collabora/whisper-live/pull/21

**Comment by zoq** [comment] 2023-07-17 18:15
Let's close this one, @mukhma0c feel free to reopen the issue if the issue isn't solved.

**Closed by zoq** 2023-07-17 18:15 UTC
